### ISSUE TITLE
HMR not working in a monorepo package that only exports shared functions

### ISSUE THREAD

**Issue by KasimAhmic** [vitejs/vite-plugin-react-swc#59] opened 2023-02-17 19:38 UTC
### Describe the bug

Currently working on migrating our monorepo to use Vite and am encountering an issue with HMR. When making changes in a package that only contains Redux logic, React hooks, and various utility functions, the entire app is reloaded. Making any changes in any other package results in HMR working properly.

The project structure follows this sort of structure:

|Name|Type|Role|Dependencies|
|-|-|-|-|
|@ahmic/vite-repro||Root project|None|
|@ahmic/commons|Library|Redux logic, hooks, utils|None|
|@ahmic/components|Library|Re-exported MUI components and other UI components|`@ahmic/commons`|
|@ahmic/app|App|User facing app|`@ahmic/commons` and `@ahmic/components`|

Additionally, I noticed this comment on another issue (https://github.com/vitejs/vite-plugin-react/issues/75#issuecomment-1368514653) that suggests HMR only works for files with components however, modifying hooks and pure functions in my `@ahmic/app` project results in HMR working just fine.

### Reproduction

https://github.com/KasimAhmic/vite-repro

### Steps to reproduce

1. Run `yarn run init`
2. Run `yarn start`
3. Make a change in a hook and component in `@ahmic/components`
   - HMR works
4. Make a change in a hook and component in `@ahmic/app`
   - HMR works
5. Make a change in a hook in `@ahmic/commons`
   - HMR DOES NOT work, the page fully reloads instead

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 16.71 GB / 31.92 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.46)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment] 2023-02-18 00:22
This is mostly related to how Vite handles HMR. The babel plugin has some differences that could make this pattern even worse.

I'm closing this as work as intended. Even if I understand that it would be great to support this pattern, this is almost impossible to integrate in the current state of Vite.

I'm planning to add caching to the the plugin at one point, this would help for this kind of updates that invalidates a lot of files without changing the transformation output.

**Closed by ArnaudBarre** 2023-02-18 00:22 UTC
