### ISSUE TITLE
Unbound breakpoints while debugging React + TS + SWC inside VSCode

### ISSUE THREAD

**Issue by Moshyfawn** [vitejs/vite-plugin-react-swc#13] opened 2022-12-09 16:13 UTC
# Description

Using VSCode debugger, when setting a breakpoint and running the debugger, the breakpoint is unbound and the app execution doesn't break

<img width="339" alt="image" src="https://user-images.githubusercontent.com/16290753/206744497-863dfd58-9b47-44d2-bfae-50bfbc1c54e0.png">

# Environment

- VSCode Insiders: _1.74.0-insider_
- MacOS: _13.0.1_

# Dependencies

```json
{
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^18.11.12",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "@vitejs/plugin-react-swc": "^3.0.0",
    "typescript": "^4.9.3",
    "vite": "^4.0.0"
  }
}
```

# Vite config

```js
import { defineConfig } from "vite"
import react from "@vitejs/plugin-react-swc"

export default defineConfig({
  plugins: [react()]
})
```

**Comment by ArnaudBarre** [comment] 2022-12-09 17:50
Thanks for the report, I will look at it

**Comment by Moshyfawn** [comment] 2022-12-09 17:56
> Thanks for the report, I will look at it

Appreciate it! Let me know if you need any more info; I'm not sure what can be useful for this issue

**Comment by ArnaudBarre** [comment] 2022-12-10 12:26
I'm not using VSCoode, but here is the config I used to try to reproduce:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:5173",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```

I was able to set a breakpoint in the render of the component:

<img width="373" alt="Screenshot 2022-12-10 at 13 25 37" src="https://user-images.githubusercontent.com/14235743/206854987-82e2b3c1-1b42-42b8-b363-fbcdfaf576ff.png">

What is your debug setup?

**Comment by ArnaudBarre** [comment] 2022-12-27 21:52
Closing as can't reproduce. Feel free to reopen if you have more details on how to reproduce.

**Closed by ArnaudBarre** 2022-12-27 21:52 UTC
