### ISSUE TITLE
React refresh preamble was not loaded

### ISSUE THREAD

**Issue by ianschmitz** [vitejs/vite-plugin-react-swc#28] opened 2022-12-15 20:38 UTC
Hi all! 👋 

While migrating to Vite 4, i decided i would try this plugin as a replacement of `@vitejs/plugin-react`. When trying to load the page i get the following error:

![image](https://user-images.githubusercontent.com/6355370/207961936-348e7b57-b46a-42de-a65c-96f270911c6d.png)

Swapping back to `plugin-react` fixes the error. Let me know if there's any specific information i can provide to help debug!

**Comment by ArnaudBarre** [comment] 2022-12-16 14:52
The second error is cause by the first one. That's difficult to know why it happened without a reproduction

**Comment by ArnaudBarre** [comment] 2022-12-27 14:04
Closing as can't reproduce. Feel free to reopen if you have a repro.

**Closed by ArnaudBarre** 2022-12-27 14:04 UTC

**Comment by enpitsuLin** [comment] 2023-01-11 02:05
this problem maybe cause by some other vite plugin in your project assigning a value to globalThis.__dirname same like [this](https://github.com/magne4000/vite-plugin-vercel/issues/9)

https://github.com/vitejs/vite-plugin-react-swc/blob/786826fb81459d7e088703a048d5523f2841f7cd/src/index.ts#L16-L19

**Comment by ArnaudBarre** [comment] 2023-01-11 08:07
This is for cjs compatibility. I need to check but I think `import.meta.url` is not defined.

This is also what antfu uses: https://antfu.me/posts/isomorphic-dirname

This issue for me would be to override a variable with a very specific meaning in cjs. What's the goal of this?

**Comment by quantuminformation** [comment] 2023-04-06 07:19
I just got this today, using a fresh vite repo

**Comment by mikeumus** [comment] 2024-07-06 19:42
@quantuminformation @ianschmitz @ArnaudBarre @enpitsuLin @yyx990803 did anyone ever find an solution to this. I'm facing it now and it's a booger. 👻

**Comment by quantuminformation** [comment] 2024-07-06 23:50
I gave up

**Comment by ArnaudBarre** [comment] 2024-07-08 09:33
@mikeumus There can be a lot of reason that causes this issue. Try to understand what file causes the issue and what is special about it and reproduce it starting from a new Vite + react-swc template
