### ISSUE TITLE
HMR is not working when `base` option in vite.config.ts is not `'/'`

### ISSUE THREAD

**Issue by wand2016** [vitejs/vite-plugin-react-swc#27] opened 2022-12-14 11:50 UTC
```diff
  export default defineConfig({
-   base: '/',
+   base: '/elsewhere/',
    ...
```

HMR is not working when `base` option in vite.config.ts is not `'/'`.

**Comment by ArnaudBarre** [comment] 2022-12-14 12:26
Duplicate of #18, fixed in main, will be available in next patch (probably in a few days)!

**Closed by ArnaudBarre** 2022-12-14 12:26 UTC
